"""Tests for the v12.4 Python pivot — async/decorator extraction,
generated-dir exclusion, Python idiom detectors.

Each test corresponds to a finding from the dogfood pass on
``deep-research`` / ``roam-agent-eval`` so the fix doesn't regress.
"""

from __future__ import annotations

from tree_sitter_language_pack import get_parser

from roam.languages.python_lang import PythonExtractor
from roam.output.file_role_hints import header_indicates_generated, is_excluded_path

# ---------------------------------------------------------------------------
# is_async + decorators on Python symbols
# ---------------------------------------------------------------------------


def _extract(source: bytes) -> list[dict]:
    parser = get_parser("python")
    tree = parser.parse(source)
    return PythonExtractor().extract_symbols(tree, source, "test.py")


class TestAsyncDetection:
    """``async def`` should set ``is_async=True`` on the symbol."""

    def test_async_function_marked_async(self):
        symbols = _extract(b"async def cook(x): return x\n")
        cook = next(s for s in symbols if s["name"] == "cook")
        assert cook["is_async"] is True

    def test_sync_function_not_marked_async(self):
        symbols = _extract(b"def sync_fn(x): return x\n")
        sym = next(s for s in symbols if s["name"] == "sync_fn")
        assert sym["is_async"] is False

    def test_async_method_in_class_marked_async(self):
        source = b"class A:\n    async def run(self): pass\n"
        symbols = _extract(source)
        run = next(s for s in symbols if s["name"] == "run")
        assert run["kind"] == "method"
        assert run["is_async"] is True

    def test_decorated_async_method_marked_async(self):
        """A decorated ``async def`` is wrapped in decorated_definition;
        the async detection must drill into the inner function."""
        source = b"import functools\n@functools.wraps(None)\nasync def cached(): pass\n"
        symbols = _extract(source)
        cached = next(s for s in symbols if s["name"] == "cached")
        assert cached["is_async"] is True
        assert "@functools.wraps" in cached.get("decorators", "")


class TestDecoratorExtraction:
    """Decorators above ``def`` / ``class`` get joined into the
    ``decorators`` field comma-separated."""

    def test_property_decorator_captured(self):
        source = b"class A:\n    @property\n    def x(self): return 1\n"
        symbols = _extract(source)
        x = next(s for s in symbols if s["name"] == "x")
        assert "@property" in x.get("decorators", "")

    def test_pytest_fixture_decorator_captured(self):
        source = b"import pytest\n@pytest.fixture\ndef client(): pass\n"
        symbols = _extract(source)
        client = next(s for s in symbols if s["name"] == "client")
        assert "@pytest.fixture" in client.get("decorators", "")

    def test_undecorated_has_empty_decorators(self):
        source = b"def plain(): pass\n"
        symbols = _extract(source)
        plain = next(s for s in symbols if s["name"] == "plain")
        assert plain.get("decorators", "") == ""


# ---------------------------------------------------------------------------
# Generated-dir / file-role hint detection
# ---------------------------------------------------------------------------


class TestFileRoleHints:
    """``output.file_role_hints.is_excluded_path`` covers the canonical
    excluded-from-headline paths."""

    def test_examples_dir_excluded(self):
        assert is_excluded_path("examples/quickstart.py") is True

    def test_workspaces_dir_excluded(self):
        """Surfaced 2026-05-02 R-pivot — ``workspaces/`` are agent-
        generated benchmark artifacts, not source code."""
        assert is_excluded_path("workspaces/agent/foo/main.py") is True

    def test_dev_dir_excluded(self):
        assert is_excluded_path("dev/repo_hygiene.py") is True

    def test_github_dir_excluded(self):
        assert is_excluded_path(".github/scripts/pr-comment.js") is True

    def test_benchmarks_dir_excluded(self):
        assert is_excluded_path("benchmarks/agent-eval/compare.py") is True

    def test_node_modules_excluded(self):
        assert is_excluded_path("node_modules/foo/index.js") is True

    def test_vendor_dir_excluded(self):
        assert is_excluded_path("vendor/third_party/lib.py") is True

    def test_normal_source_not_excluded(self):
        assert is_excluded_path("src/roam/cli.py") is False
        assert is_excluded_path("tests/test_foo.py") is False

    def test_empty_path_not_excluded(self):
        assert is_excluded_path("") is False

    def test_windows_separators_normalised(self):
        assert is_excluded_path("workspaces\\agent\\foo.py") is True


class TestGeneratedHeaderDetection:
    def test_protobuf_marker(self):
        text = "// Code generated by protoc. DO NOT EDIT.\npackage foo\n"
        assert header_indicates_generated(text) is True

    def test_at_generated_tag(self):
        text = '"""@generated by some-tool"""\nimport foo\n'
        assert header_indicates_generated(text) is True

    def test_normal_file_not_generated(self):
        text = '"""A normal Python module."""\nimport foo\n'
        assert header_indicates_generated(text) is False

    def test_empty_text(self):
        assert header_indicates_generated("") is False


# ---------------------------------------------------------------------------
# Python idiom detectors (regex-based)
# ---------------------------------------------------------------------------


class TestPythonIdiomRegexes:
    """Sanity-check the regex patterns directly without spinning up a DB."""

    def test_mutable_default_list_matches(self):
        from roam.catalog.python_idioms import _MUTABLE_DEFAULT_RE

        assert _MUTABLE_DEFAULT_RE.search("def f(x=[])") is not None
        assert _MUTABLE_DEFAULT_RE.search("def g(d={})") is not None
        assert _MUTABLE_DEFAULT_RE.search("def h(x=list())") is not None
        assert _MUTABLE_DEFAULT_RE.search("def k(s=set())") is not None

    def test_immutable_default_does_not_match(self):
        from roam.catalog.python_idioms import _MUTABLE_DEFAULT_RE

        assert _MUTABLE_DEFAULT_RE.search("def f(x=None)") is None
        assert _MUTABLE_DEFAULT_RE.search('def g(s="")') is None
        assert _MUTABLE_DEFAULT_RE.search("def h(n=0)") is None
        assert _MUTABLE_DEFAULT_RE.search("def k(t=())") is None

    def test_bare_except_matches(self):
        from roam.catalog.python_idioms import _BARE_EXCEPT_RE

        assert _BARE_EXCEPT_RE.search("try:\n    x()\nexcept:\n    pass\n") is not None
        # Indented bare except inside a function
        assert _BARE_EXCEPT_RE.search("def f():\n    try:\n        x()\n    except:\n        pass\n") is not None

    def test_typed_except_does_not_match(self):
        from roam.catalog.python_idioms import _BARE_EXCEPT_RE

        assert _BARE_EXCEPT_RE.search("try:\n    x()\nexcept ValueError:\n    pass\n") is None
        assert _BARE_EXCEPT_RE.search("try:\n    x()\nexcept (A, B) as e:\n    pass\n") is None

    def test_none_eq_matches(self):
        from roam.catalog.python_idioms import _NONE_EQ_RE

        assert _NONE_EQ_RE.search("if x == None:") is not None
        assert _NONE_EQ_RE.search("if x != None:") is not None

    def test_none_is_does_not_match(self):
        from roam.catalog.python_idioms import _NONE_EQ_RE

        assert _NONE_EQ_RE.search("if x is None:") is None

    def test_logger_fstring_matches(self):
        from roam.catalog.python_idioms import _LOGGER_FSTRING_RE

        assert _LOGGER_FSTRING_RE.search('logger.info(f"x={x}")') is not None
        assert _LOGGER_FSTRING_RE.search('log.warning(f"oops")') is not None
        assert _LOGGER_FSTRING_RE.search("logging.debug(f'fmt')") is not None
        assert _LOGGER_FSTRING_RE.search('self.logger.error(f"x")') is not None

    def test_logger_lazy_format_does_not_match(self):
        from roam.catalog.python_idioms import _LOGGER_FSTRING_RE

        assert _LOGGER_FSTRING_RE.search('logger.info("x=%s", x)') is None
        assert _LOGGER_FSTRING_RE.search('logger.info("plain")') is None
