"""Generate CI/CD pipeline configurations for roam-code integration."""

from __future__ import annotations

from pathlib import Path

import click

from roam.output.formatter import json_envelope, to_json

# ── Platform definitions ─────────────────────────────────────────────

_PLATFORMS = {
    "github": {
        "description": "GitHub Actions",
        "detect_paths": [".github/workflows"],
        "output_path": ".github/workflows/roam.yml",
        "template_file": None,  # GitHub uses the composite action, not a template file
    },
    "gitlab": {
        "description": "GitLab CI/CD",
        "detect_paths": [".gitlab-ci.yml"],
        "output_path": ".gitlab-ci.roam.yml",
        "template_file": "gitlab-ci.yml",
    },
    "azure": {
        "description": "Azure DevOps Pipelines",
        "detect_paths": ["azure-pipelines.yml", "azure-pipelines"],
        "output_path": "azure-pipelines.roam.yml",
        "template_file": "azure-pipelines.yml",
    },
    "jenkins": {
        "description": "Jenkins",
        "detect_paths": ["Jenkinsfile", "jenkins", "Jenkinsfile.d"],
        "output_path": "Jenkinsfile.roam",
        "template_file": "Jenkinsfile",
    },
    "bitbucket": {
        "description": "Bitbucket Pipelines",
        "detect_paths": ["bitbucket-pipelines.yml"],
        "output_path": "bitbucket-pipelines.roam.yml",
        "template_file": "bitbucket-pipelines.yml",
    },
}

# ── GitHub Actions template (inline — uses the composite action) ─────

_GITHUB_TEMPLATE = """\
# roam-code Analysis for GitHub Actions
#
# Runs roam-code health checks and rules validation on pull requests.
# Posts a sticky PR comment and uploads SARIF to GitHub Code Scanning.
#
# To customize: adjust commands, gate threshold, and sarif-commands below.
# Generated by: roam ci-setup --platform github

name: roam-code Analysis

on:
  pull_request:
    branches: [main, master]

permissions:
  contents: read
  pull-requests: write
  security-events: write  # Required for SARIF upload

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history needed for pr-risk and git analysis

      - uses: Cranot/roam-code@main
        with:
          commands: 'health check-rules pr-risk'
          sarif: 'true'
          sarif-commands: 'health'
          sarif-category: 'roam-code'
          comment: 'true'
          gate: 'health_score>=60'
          python-version: '{python_version}'
"""


# ── Template loading ─────────────────────────────────────────────────


def _templates_dir() -> Path:
    """Return the path to the bundled CI templates directory."""
    return Path(__file__).resolve().parent.parent / "templates" / "ci"


def _load_template(platform: str) -> str:
    """Load and return the template content for a given platform."""
    if platform == "github":
        return _GITHUB_TEMPLATE

    cfg = _PLATFORMS[platform]
    template_file = cfg["template_file"]
    template_path = _templates_dir() / template_file
    if not template_path.exists():
        raise click.ClickException(
            f"Template file not found: {template_path}\nThis is a packaging error. Please reinstall roam-code."
        )
    return template_path.read_text(encoding="utf-8")


def _substitute_vars(template: str, variables: dict[str, str]) -> str:
    """Perform variable substitution on template content.

    Uses {variable_name} placeholders.  Only substitutes variables that
    are present in the template (safe — does not fail on missing keys).
    """
    result = template
    for key, value in variables.items():
        result = result.replace(f"{{{key}}}", value)
    return result


# ── Platform detection ───────────────────────────────────────────────


def _detect_platform(project_root: Path) -> list[str]:
    """Detect CI platforms present in the project.

    Returns a list of platform names (may be empty or have multiple).
    """
    detected = []
    for name, cfg in _PLATFORMS.items():
        for detect_path in cfg["detect_paths"]:
            full_path = project_root / detect_path
            if full_path.exists():
                detected.append(name)
                break
    return detected


def _get_project_name(project_root: Path) -> str:
    """Derive a project name from the project root directory."""
    return project_root.name


def _get_python_version() -> str:
    """Return a sensible default Python version string."""
    return "3.12"


def _get_default_branch(project_root: Path) -> str:
    """Try to detect the default branch from git config."""
    # Check for common branch names
    git_dir = project_root / ".git"
    if git_dir.is_dir():
        head_ref = git_dir / "refs" / "heads" / "main"
        if head_ref.exists():
            return "main"
        head_ref = git_dir / "refs" / "heads" / "master"
        if head_ref.exists():
            return "master"
    return "main"


# ── CLI command ──────────────────────────────────────────────────────


@click.command("ci-setup")
@click.option(
    "--platform",
    type=click.Choice(sorted(_PLATFORMS.keys())),
    default=None,
    help="CI platform (auto-detected if omitted).",
)
@click.option(
    "--write",
    "write_file",
    is_flag=True,
    default=False,
    help="Write the template to the project (instead of printing).",
)
@click.option(
    "--python-version",
    default=None,
    help="Python version to use in the template (default: 3.12).",
)
@click.option(
    "--gate",
    default="60",
    help="Minimum health score for quality gate (default: 60).",
)
@click.pass_context
def ci_setup(ctx, platform, write_file, python_version, gate):
    """Generate CI/CD pipeline config for roam-code integration.

    Produces ready-to-commit pipeline YAML for GitHub Actions, GitLab CI,
    Azure Pipelines, Jenkins, and Bitbucket.  Auto-detects the CI platform
    from marker files or use --platform to specify one.

    Unlike ``mcp-setup`` (which generates MCP server JSON configs), this
    command generates full CI pipeline files that run ``roam health``,
    ``roam check-rules``, and ``roam pr-risk`` on every pull request.

    \b
    Platforms:
      github      GitHub Actions (composite action)
      gitlab      GitLab CI/CD
      azure       Azure DevOps Pipelines
      jenkins     Jenkins (Declarative Pipeline)
      bitbucket   Bitbucket Pipelines

    \b
    Examples:
      roam ci-setup                        # auto-detect + show template
      roam ci-setup --platform gitlab      # show GitLab template
      roam ci-setup --platform azure --write  # write Azure template
      roam --json ci-setup --platform github  # JSON output
    """
    json_mode = ctx.obj.get("json") if ctx.obj else False

    # Find project root
    try:
        from roam.db.connection import find_project_root

        project_root = find_project_root()
    except Exception:
        project_root = Path.cwd()

    project_name = _get_project_name(project_root)
    py_version = python_version or _get_python_version()
    default_branch = _get_default_branch(project_root)

    # Template variables for substitution
    variables = {
        "project_name": project_name,
        "python_version": py_version,
        "default_branch": default_branch,
        "health_gate": gate,
    }

    # Detect or use specified platform
    detected = _detect_platform(project_root)

    if platform is None:
        if not detected:
            # No platform detected — list all options
            if json_mode:
                click.echo(
                    to_json(
                        json_envelope(
                            "ci-setup",
                            summary={
                                "verdict": "No CI platform detected",
                                "detected": [],
                                "hint": "Use --platform to specify one",
                            },
                            platforms={name: cfg["description"] for name, cfg in sorted(_PLATFORMS.items())},
                        )
                    )
                )
                return

            click.echo("No CI platform detected in this project.\n")
            click.echo("Supported platforms:\n")
            for name, cfg in sorted(_PLATFORMS.items()):
                click.echo(f"  {name:12s} {cfg['description']}")
            click.echo("\nUsage: roam ci-setup --platform <name>")
            click.echo("  Add --write to write the template file to your project.")
            return

        if len(detected) > 1:
            # Multiple platforms detected — ask user to pick
            if json_mode:
                click.echo(
                    to_json(
                        json_envelope(
                            "ci-setup",
                            summary={
                                "verdict": f"{len(detected)} CI platforms detected",
                                "detected": detected,
                                "hint": "Use --platform to select one",
                            },
                            detected=[
                                {
                                    "platform": d,
                                    "description": _PLATFORMS[d]["description"],
                                }
                                for d in detected
                            ],
                        )
                    )
                )
                return

            click.echo(f"Multiple CI platforms detected ({len(detected)}):\n")
            for d in detected:
                click.echo(f"  {d:12s} {_PLATFORMS[d]['description']}")
            click.echo("\nUse --platform <name> to select one.")
            return

        # Exactly one platform detected
        platform = detected[0]

    # Load template
    cfg = _PLATFORMS[platform]
    template = _load_template(platform)
    rendered = _substitute_vars(template, variables)

    output_path = cfg["output_path"]
    abs_output_path = project_root / output_path

    if write_file:
        # Write the template to the project
        abs_output_path.parent.mkdir(parents=True, exist_ok=True)

        if abs_output_path.exists():
            if json_mode:
                click.echo(
                    to_json(
                        json_envelope(
                            "ci-setup",
                            summary={
                                "verdict": f"File already exists: {output_path}",
                                "platform": platform,
                                "path": output_path,
                                "action": "skipped",
                            },
                        )
                    )
                )
                return

            click.echo(f"File already exists: {output_path}")
            click.echo("Remove it first or manually merge the template below:\n")
            click.echo(rendered)
            return

        abs_output_path.write_text(rendered, encoding="utf-8")

        if json_mode:
            click.echo(
                to_json(
                    json_envelope(
                        "ci-setup",
                        summary={
                            "verdict": f"Wrote {cfg['description']} template",
                            "platform": platform,
                            "path": output_path,
                            "action": "created",
                        },
                        platform=platform,
                        description=cfg["description"],
                        path=output_path,
                        variables=variables,
                    )
                )
            )
            return

        click.echo(f"Wrote {cfg['description']} template to: {output_path}\n")
        _print_post_setup_instructions(platform, output_path)
        return

    # Print template (no --write)
    if json_mode:
        click.echo(
            to_json(
                json_envelope(
                    "ci-setup",
                    summary={
                        "verdict": f"Template for {cfg['description']}",
                        "platform": platform,
                        "detected": detected,
                    },
                    platform=platform,
                    description=cfg["description"],
                    output_path=output_path,
                    template=rendered,
                    variables=variables,
                )
            )
        )
        return

    click.echo(f"=== {cfg['description']} template ===\n")
    if platform in detected:
        click.echo(f"(Detected: {cfg['detect_paths'][0]} exists in project)\n")
    click.echo(rendered)
    click.echo(f"\n--- Save as: {output_path} ---")
    click.echo(f"Or run: roam ci-setup --platform {platform} --write")


def _print_post_setup_instructions(platform: str, output_path: str) -> None:
    """Print platform-specific instructions after writing the template."""
    instructions = {
        "github": [
            "Next steps:",
            "  1. Commit and push .github/workflows/roam.yml",
            "  2. Open a pull request to trigger the analysis",
            "  3. Check the PR comment for health score and SARIF findings",
            "",
            "Permissions required: contents:read, pull-requests:write, security-events:write",
        ],
        "gitlab": [
            "Next steps:",
            f"  1. Rename {output_path} to .gitlab-ci.yml (or include it)",
            "     To include as a separate job, add to your .gitlab-ci.yml:",
            f"       include: '{output_path}'",
            "  2. Optionally set GITLAB_TOKEN variable with api scope for MR comments",
            "     (CI_JOB_TOKEN works but may lack permissions for notes API)",
            "  3. Push to trigger the pipeline",
        ],
        "azure": [
            "Next steps:",
            f"  1. Rename {output_path} to azure-pipelines.yml (or reference it)",
            "     To use as a separate pipeline, create a new pipeline in Azure DevOps",
            f"     pointing to {output_path}",
            "  2. Ensure 'Contribute to pull requests' permission is enabled for the",
            "     build service identity (for PR comments)",
            "  3. Push to trigger the pipeline",
        ],
        "jenkins": [
            "Next steps:",
            f"  1. Rename {output_path} to Jenkinsfile (or load it from your main Jenkinsfile)",
            "  2. Install 'Warnings Next Generation' plugin for SARIF ingestion:",
            "     https://plugins.jenkins.io/warnings-ng/",
            "  3. Ensure Python 3.9+ is available on the Jenkins agent",
            "  4. Trigger a build to test the pipeline",
        ],
        "bitbucket": [
            "Next steps:",
            f"  1. Rename {output_path} to bitbucket-pipelines.yml (or merge into existing)",
            "  2. Enable Pipelines in Repository Settings",
            "  3. Optionally set ROAM_HEALTH_GATE repository variable",
            "  4. Open a pull request to trigger the analysis",
        ],
    }

    for line in instructions.get(platform, []):
        click.echo(line)
